name: canneapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.7.2

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3
  mobile_scanner: ^6.0.10
  qr_flutter: ^4.1.0
  http: ^1.3.0
  shelf: ^1.4.2
  network_info_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/cane_icon.png"